# Generated by Django 4.0.3 on 2022-04-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('code', models.CharField(max_length=10)),
                ('closed_price', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
